---
- name: Configure and Install Consul
  block:
    - name: Download CONSUL Binaries
      get_url:
        url: https://releases.hashicorp.com/consul/1.2.3/consul_1.2.3_linux_amd64.zip
        dest: /tmp/consul_1.2.3_linux_amd64.zip

    - name: Extract Binaries
      unarchive:
        src: /tmp/consul_1.2.3_linux_amd64.zip
        dest: /usr/bin
        remote_src: yes

    - name: Remove the download
      file:
        path: /tmp/consul_1.2.3_linux_amd64.zip
        state: absent

    - name: Create Consul User
      user:
        name: consul
        shell: /usr/sbin/nologin
        system: yes
        createhome: no

    - name: Create Consul Directory
      file:
        path: /var/lib/consul
        state: directory
        owner: consul
        group: consul
        mode: 0755

    - name: Upload SystemD Unit
      copy:
        src: templates/consul.service
        dest: /usr/lib/systemd/user/consul.service

    - name: Insert Consul in DNS Lookup
      copy:
        src: templates/resolved.conf
        dest: /etc/systemd/resolved.conf

    - name: Update HCL
      template:
        src: templates/consul.j2.hcl
        dest: /etc/consul.hcl
        owner: consul
        group: consul
        mode: 0644

    - name: Enable Consul Unit at Boot
      command: systemctl enable /usr/lib/systemd/user/consul.service

