---
- name: Configure and allow Passwordless Login for punch user
  block:
    - name: Add punch user
      user:
        name: punch
        shell: /usr/sbin/nologin
        append: yes
        state: present
        createhome: no

    - name: Set the password to empty
      command: passwd -d punch

    - name: Add no-login stanza to sshd config
      copy:
        src: templates/sshd_config
        dest: /etc/ssh/sshd_config

    - name: Allow users in /etc/ssh/autologin to login automatically
      copy:
        src: templates/pam_ssh
        dest: /etc/pam.d/sshd

    - name: Populate /etc/ssh/autologin with punch
      lineinfile:
        path: /etc/ssh/autologin
        line: 'punch'
        create: yes
