---
dependency:
  name: galaxy
driver:
  name: delegated
lint:
  name: yamllint
platforms:
  - name: dmz
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      dmz:
        ansible_python_interpreter: "/usr/bin/python3"
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  name: dmz
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
