---
- name: Provisioning
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    env: prod
    district: dmz
    consul_district: city
    logo: shiva
    datadog_tags:
      - load_balancer

  roles:
    - amazon
    - common
    - consul_client
    - public_ssh
    - fabio
