# Common Tasks to Prep the template system to receive ansible provisioning

---
- name: Clear the mechanism
  apt:
    update_cache: yes

- name: Skip DNS for `localhost`
  copy:
    dest: /etc/hosts
    content: |
      127.0.0.1	localhost

- name: Set Default Local
  copy:
    dest: /etc/default/locale
    content: |
      LC_CTYPE="en_US.UTF-8"
      LC_ALL="en_US.UTF-8"
      LANG="en_US.UTF-8"

- name: Set the Vault Addr Globally
  lineinfile:
    path: /etc/environment
    regexp: '^VAULT_ADDR='
    line: 'VAULT_ADDR=http://vault:8200'
    create: yes

- name: Disable unattended upgrades while we're ansibiling
  block:
    - command: systemctl disable apt-daily.service
    - command: systemctl disable apt-daily.timer

- name: Install Unzip
  apt:
    name: unzip
    state: present
    update_cache: yes

- name: Install AppArmor
  apt:
    pkg: apparmor
    state: present
