---
- name: Create regular login user
  block:
    - name: Create login user
      user:
        name: alan
        shell: /bin/bash
        groups:
          - adm
          - sudo

    - name: Ensure .ssh config directory
      file:
        path: /home/alan/.ssh
        recurse: yes
        owner: alan
        group: alan
        mode: 0700

    - name: Copy the provisioning key over
      authorized_key: user=alan key="{{item}}"
      with_file:
        - ../provision.pub

    - name: Add a sudoer file
      file:
        path: /etc/sudoers.d/00-login-user
        state: touch

    - name: Add the login user
      lineinfile:
        dest: /etc/sudoers.d/00-login-user
        state: present
        line: 'alan ALL=(ALL) NOPASSWD: ALL'

    - name: Copy Ubuntu's bashrc
      copy:
        src: /home/ubuntu/.bashrc
        dest: /home/alan/.bashrc
        owner: alan
        group: alan
        mode: 0644
        remote_src: true

    - name: Copy Ubuntu's profile
      copy:
        src: /home/ubuntu/.bashrc
        dest: /home/alan/.profile
        owner: alan
        group: alan
        mode: 0644
        remote_src: true
