---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not (lookup('env', 'MOLECULE_DEBUG') | bool or molecule_yml.provisioner.log|default(false) | bool) }}"
  tasks:

    - name: Get workspace name
      shell: |
        if [[ -z "${WORKSPACE_NAME}" ]]; then
          cat {{ playbook_dir }}/../../../.terraform/environment
        else
          echo ${WORKSPACE_NAME}
        fi
      args:
        executable: /bin/bash
      register: workspace_name

    - name: Print workspace name
      debug: msg={{ workspace_name.stdout }}

    - name: Populate instance config dict
      set_fact:
        instance_conf_dict: {
          'instance': "{{ item.name }}",
          'address': "{{ item.name }}{{ workspace_name.stdout }}{{ lookup('env','SEARCH_DOMAIN') }}",
          'user': "alan", }
      register: instance_config_dict
      with_items: "{{ molecule_yml.platforms }}"

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
