---
- name: Gather Auth Methods
  environment:
    VAULT_TOKEN: "{{ vault_token }}"

  block:
    - command: 'vault auth list -format json'
      register: auth_list

    - set_fact:
        auth_methods: "{{ auth_list.stdout | from_json | json_query('keys(@)') }}"

    - command: 'vault policy list -format json'
      register: policy_list_raw

    - set_fact:
        policy_list: "{{ policy_list_raw.stdout | from_json }}"

    - command: 'vault secrets list -format json'
      register: secrets_list_raw

    - set_fact:
        secrets_list: "{{ secrets_list_raw.stdout | from_json | json_query('keys(@)') }}"


