---
- name: Setup Nomad Policies
  environment:
    VAULT_TOKEN: "{{ vault_token }}"
  when: "'nomad-policy' not in policy_list"
  block:
    - name: Write Nomad Policy to vault
      command: "vault policy write nomad-policy {{role_path}}/templates/nomad-policy.hcl"

    - name: Write Token Role to Vault
      command: "vault write /auth/token/roles/nomad-cluster @{{role_path}}/templates/nomad-cluster-role.json"


