- name: Unseal and Initialize the Vault
  block:
    - name: Register the Vault Initialization Status
      command: vault status -format=json
      ignore_errors: yes
      register: vault_status

    - name: Set Vault Status
      set_fact:
        vault_init_status: "{{ vault_status.stdout | from_json | json_query('initialized')}}"

    - name: Initialize Vault if'n ya need
      when: not vault_init_status

      block:
        - name: Initialize Vault and Autounseal
          command: vault operator init
          register: recovery_keys

        - name: Write the recovery_keys to kbfs on the provisioning host
          copy:
            content: "{{recovery_keys.stdout}}"
            dest: "{{ output_directory }}/vault_recovery"

    - set_fact:
        vault_token: "{{ lookup('file',vars['output_directory'] + '/vault_recovery') | regex_search('Initial Root Token: (.*)','\\1') | first }}"

    - debug:
        msg: "{{vault_token}}"

    - name: Login to Vault
      command: "vault login {{vault_token}}"





