---
- name: Provisioning
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  vars:
    # replace me with an EC2 autoscale lookup
    cluster_size: 3
    # replace me with an env lookup
    env: prod
    district: city
    consul_district: city
    logo: city
    datadog_tags:
      - host

  roles:
    - amazon
    - common
    - consul_server
    - docker
    - nomad_server
