#cloud-config
---
system_info:
  default_user:
    name: alan

ssh_import_id:
  - gh:stephenprater
  - gh:AndrewScibek
  - gh:corbinlc
  - gh:MatthewTighe

hostname: ${hostname}

bootcmd:
  - 'sed -i "s/datacenter.*/datacenter = \"${lb_district}\"/" /etc/consul.hcl'
