#cloud-config
---
system_info:
  default_user:
    name: alan

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsyDvFpGurHAFb0bEIksovsIBPolkcf8whk21L9jf5IgMqevRcn0KgDsylXMUmK1+F9ro8eE9CcGAeD+vzPpnqovs9mJSlC8pkmGCgHfmUsmZr7vuPkOkBQ2ltntuSfmnt5mhlM8U4ybfsYKOPg+qY+SjcTjeHEzCTlxRiPLixDTvKdznJ7kO/XrqTg28RfIPCKimEbyvPiPJNM5UJfjx45QayyGddnOOuOMlnMEOM/e42gpGvaabQPGUyRtoFtpGD6i5JyrNoV2Tu+lp3XZfp6qdyzcbZBFcV7H7ZP9F/0ng3emwqEvw77DnWBTVXSqFe8MX0aQLUGuOP60PnQsaX stephenprater@tnuctip.local
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCql7zhMUOAdsd6mFdBT4Nm9rhHqmWqF9x++mRBW5dUDI7JbXtMQ18/d496VSUmdj0iEoWPLY73hTagIlX3o/vjfcmBqZ016t1zNDthCPvVlhCcR8kk9JvYGC23YplbqrBl7teXeVFutzAyTKdOkZY0MjM4HaNfkM3J7c0lOcizA5ygpCyQ0BpiVumbVENpS6/XPPhcP4oQDizWiSw96Tl0wyqdlB6MeGOXODbYi9GPYopwEGGR5UqjtzjfzOKGRtUQuB+NUIXGAJBmsTNxBB0v1OPr5vFgnF4ux8ayjJys946jP94cMZu8GGpSWueQCQwFMFU3syE1cBfPVtpEvkZ9 schafer@CLSchaferUL

hostname: ${hostname}

write_files:
  - path: /etc/ssh/import_keys
    content: |
      gh:stephenprater
      gh:AndrewScibek
      gh:corbinlc
      gh:MatthewTighe
      gh:luongthomas
