#cloud-config
---
system_info:
  default_user:
    name: alan

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDpTXS/EDoTbUBzfG+lKvprS+lbLsvVS1IDyUj02H5+8crQWqJTw/AVxtOulzItTYBAaEjtJIURMrtYICH1vqAceTbtrxH/pvdce86DJe4fgKQlEZ0Xyu9fjItQaVkFy1RD/+q9wifJpBU+hWInL9nscysKylety/rOS+3o6EWIW8AeJ1dguLwWLejOghtyJOP2hpenqdrLWFqzkwfbdG0NaOI8xcCgJuvR7HNPg1rrjLMK4fn6Ms87Sj5IBYhcA62ZrP4D63lLQs0c4YhfFrQkICHVtmcOLQCb59BFP/FndHBNKtCO0QoA3bva9+eoPQirF82hjrurOt/WNplwocg10ffHug3AnKxpLcfwHVjiHxYyn7BmgDrO0hBCvfOw/2nTQhCP73ervGjF6Lq83YVLMtpdYxY2pqIKZfuuiDw3GyldnSe6yXBZiFda7eWqNCrkBI1qTrt3YtjJGASMa9G3YSPPHif4jkmvnK+0isU9a8ZgUiurTmr95x3dhtEhWNOFPCxhRmQhl42XxJhWkRUtS6UylHybILci3cw2pmeJTnfuFX4zU3cLoiv2jOLI57wUoaq+CsqQgwY9ocwSY0ivGkpC4ImprCriqsbKkoUePS3wqTSGqSQBgaBVDUVdxRJjEotkhKNu3uK63ECho85+kb01cWjhRvC4ZkwLLzOh3w== corbinlc@gmail.com
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsyDvFpGurHAFb0bEIksovsIBPolkcf8whk21L9jf5IgMqevRcn0KgDsylXMUmK1+F9ro8eE9CcGAeD+vzPpnqovs9mJSlC8pkmGCgHfmUsmZr7vuPkOkBQ2ltntuSfmnt5mhlM8U4ybfsYKOPg+qY+SjcTjeHEzCTlxRiPLixDTvKdznJ7kO/XrqTg28RfIPCKimEbyvPiPJNM5UJfjx45QayyGddnOOuOMlnMEOM/e42gpGvaabQPGUyRtoFtpGD6i5JyrNoV2Tu+lp3XZfp6qdyzcbZBFcV7H7ZP9F/0ng3emwqEvw77DnWBTVXSqFe8MX0aQLUGuOP60PnQsaX stephenprater@tnuctip.local
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCql7zhMUOAdsd6mFdBT4Nm9rhHqmWqF9x++mRBW5dUDI7JbXtMQ18/d496VSUmdj0iEoWPLY73hTagIlX3o/vjfcmBqZ016t1zNDthCPvVlhCcR8kk9JvYGC23YplbqrBl7teXeVFutzAyTKdOkZY0MjM4HaNfkM3J7c0lOcizA5ygpCyQ0BpiVumbVENpS6/XPPhcP4oQDizWiSw96Tl0wyqdlB6MeGOXODbYi9GPYopwEGGR5UqjtzjfzOKGRtUQuB+NUIXGAJBmsTNxBB0v1OPr5vFgnF4ux8ayjJys946jP94cMZu8GGpSWueQCQwFMFU3syE1cBfPVtpEvkZ9 schafer@CLSchaferUL
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+TjhHNqrDNtDxCB25W8jMmq3Chq4Z2Tq7Mm93PYlVI3GHQSqCNigRsUo58Rv3gDofCV3R3IOzd7yErj2s/pjN6VWNfm3SGDRNhh73LMvj0PXPlIGkWIS740tYHmjwMLtu0iCOA2zF3jGndRcnelrjwbe+/iIxQTNcHZXlo+gtLHSdRk3q0nzhmpm87IOIPBgTpwSGvpKe5lIGZvYW/Ywx+HYOa384ZKy/CR136rIGfxmF0YfwwyEinURUoNBGi17SZ/GIp7i/YAZA1AYrb6uhKH4DwUs5RHwX0QsfoGXL3VpYT+k9w5nNM2FPwxbl9NYZqHS6OrY0jPQFY6R5/E8F matt@Matthews-MacBook-Pro.local

write_files:
  - path: /etc/ssh/import_keys
    content: |
      gh:stephenprater
      gh:AndrewScibek
      gh:corbinlc
      gh:MatthewTighe
      gh:luongthomas
      gh:xophere

hostname: ${hostname}

bootcmd:
  - 'sed -i "s/bootstrap_expect.*/bootstrap_expect = ${city_hosts}/" /etc/consul.hcl'
