#cloud-config
---
system_info:
  default_user:
    name: alan

write_files:
  - path: /etc/ssh/import_keys
    content: |
      gh:stephenprater
      gh:AndrewScibek
      gh:corbinlc
      gh:MatthewTighe
      gh:luongthomas

hostname: ${hostname}
