#cloud-config
---
system_info:
  default_user:
    name: alan

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsyDvFpGurHAFb0bEIksovsIBPolkcf8whk21L9jf5IgMqevRcn0KgDsylXMUmK1+F9ro8eE9CcGAeD+vzPpnqovs9mJSlC8pkmGCgHfmUsmZr7vuPkOkBQ2ltntuSfmnt5mhlM8U4ybfsYKOPg+qY+SjcTjeHEzCTlxRiPLixDTvKdznJ7kO/XrqTg28RfIPCKimEbyvPiPJNM5UJfjx45QayyGddnOOuOMlnMEOM/e42gpGvaabQPGUyRtoFtpGD6i5JyrNoV2Tu+lp3XZfp6qdyzcbZBFcV7H7ZP9F/0ng3emwqEvw77DnWBTVXSqFe8MX0aQLUGuOP60PnQsaX stephenprater@tnuctip.local
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUq7xnaDhksB+m6I82xqr+V9BnFoNE/mGl5d39hC4A4yjEPvcisO/WyHdYMw0n9Xa0lT7iSJvqjH6n+HGyUhQq9ZgsrwXV2UaqGzqMWSmbu+83+aP8u95rKTB7HnM2Tva+B25NsLZ3V9UKaDDRcAP6DW1JPbyMTm76tAjiwU+XBR0CqsbbpDzz6NSE8iieZ9DVyZcND0lvLbHjCZ78bcMUm3efHbCKKY5poHsqeEcAvVsNlR1NwKNbiofKXXZvKEgmp+Suf5BxsuI46weBdWZSUEPUV4qC9zHnmRO2llbqtlaaSJyufl0okIB6Sn561XOYZ98omsIHhgPaRqWuIl/Cj70GChZ+w2lXqsCm8MynSenu/Xh4OFnIrUkwzuZ0NwSgv6EJwSmWEaYZa7UlvJQCsubmTOnygaDa/g88jRQYyHL9UhfAgxyjWPe1uGbac5VxG+LoZdiLQKGDZqSPo0hdpJUJdzJOgY7ySaUEhlR0UjPIyO714L9symh95yTvu7nLiGFpXHpu7hXw+X9ygXLQNLx+fZFKcpvT8Izoc6mhkTBJ/1bFdHuyIGXmsVV+4uF7woovQDBPFPwktTwCS7aOCoROhjmFaunu1d/8MZ6iNHKsiHehJV7PIJ87hn8r6jSP4RP3NSFG5BCQH9B8heaBNUkXfY+dxZ/TJkxSz91/Kw== andrewscibek@Andrews-MacBook-Pro.local

write_files:
  - path: /etc/ssh/import_keys
    content: |
      gh:stephenprater
      gh:AndrewScibek
      gh:corbinlc
      gh:MatthewTighe
      gh:luongthomas

hostname: ${hostname}
