#cloud-config
---
system_info:
  default_user:
    name: alan

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDpTXS/EDoTbUBzfG+lKvprS+lbLsvVS1IDyUj02H5+8crQWqJTw/AVxtOulzItTYBAaEjtJIURMrtYICH1vqAceTbtrxH/pvdce86DJe4fgKQlEZ0Xyu9fjItQaVkFy1RD/+q9wifJpBU+hWInL9nscysKylety/rOS+3o6EWIW8AeJ1dguLwWLejOghtyJOP2hpenqdrLWFqzkwfbdG0NaOI8xcCgJuvR7HNPg1rrjLMK4fn6Ms87Sj5IBYhcA62ZrP4D63lLQs0c4YhfFrQkICHVtmcOLQCb59BFP/FndHBNKtCO0QoA3bva9+eoPQirF82hjrurOt/WNplwocg10ffHug3AnKxpLcfwHVjiHxYyn7BmgDrO0hBCvfOw/2nTQhCP73ervGjF6Lq83YVLMtpdYxY2pqIKZfuuiDw3GyldnSe6yXBZiFda7eWqNCrkBI1qTrt3YtjJGASMa9G3YSPPHif4jkmvnK+0isU9a8ZgUiurTmr95x3dhtEhWNOFPCxhRmQhl42XxJhWkRUtS6UylHybILci3cw2pmeJTnfuFX4zU3cLoiv2jOLI57wUoaq+CsqQgwY9ocwSY0ivGkpC4ImprCriqsbKkoUePS3wqTSGqSQBgaBVDUVdxRJjEotkhKNu3uK63ECho85+kb01cWjhRvC4ZkwLLzOh3w== corbinlc@gmail.com
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsyDvFpGurHAFb0bEIksovsIBPolkcf8whk21L9jf5IgMqevRcn0KgDsylXMUmK1+F9ro8eE9CcGAeD+vzPpnqovs9mJSlC8pkmGCgHfmUsmZr7vuPkOkBQ2ltntuSfmnt5mhlM8U4ybfsYKOPg+qY+SjcTjeHEzCTlxRiPLixDTvKdznJ7kO/XrqTg28RfIPCKimEbyvPiPJNM5UJfjx45QayyGddnOOuOMlnMEOM/e42gpGvaabQPGUyRtoFtpGD6i5JyrNoV2Tu+lp3XZfp6qdyzcbZBFcV7H7ZP9F/0ng3emwqEvw77DnWBTVXSqFe8MX0aQLUGuOP60PnQsaX stephenprater@tnuctip.local
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUq7xnaDhksB+m6I82xqr+V9BnFoNE/mGl5d39hC4A4yjEPvcisO/WyHdYMw0n9Xa0lT7iSJvqjH6n+HGyUhQq9ZgsrwXV2UaqGzqMWSmbu+83+aP8u95rKTB7HnM2Tva+B25NsLZ3V9UKaDDRcAP6DW1JPbyMTm76tAjiwU+XBR0CqsbbpDzz6NSE8iieZ9DVyZcND0lvLbHjCZ78bcMUm3efHbCKKY5poHsqeEcAvVsNlR1NwKNbiofKXXZvKEgmp+Suf5BxsuI46weBdWZSUEPUV4qC9zHnmRO2llbqtlaaSJyufl0okIB6Sn561XOYZ98omsIHhgPaRqWuIl/Cj70GChZ+w2lXqsCm8MynSenu/Xh4OFnIrUkwzuZ0NwSgv6EJwSmWEaYZa7UlvJQCsubmTOnygaDa/g88jRQYyHL9UhfAgxyjWPe1uGbac5VxG+LoZdiLQKGDZqSPo0hdpJUJdzJOgY7ySaUEhlR0UjPIyO714L9symh95yTvu7nLiGFpXHpu7hXw+X9ygXLQNLx+fZFKcpvT8Izoc6mhkTBJ/1bFdHuyIGXmsVV+4uF7woovQDBPFPwktTwCS7aOCoROhjmFaunu1d/8MZ6iNHKsiHehJV7PIJ87hn8r6jSP4RP3NSFG5BCQH9B8heaBNUkXfY+dxZ/TJkxSz91/Kw== andrewscibek@Andrews-MacBook-Pro.local
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCql7zhMUOAdsd6mFdBT4Nm9rhHqmWqF9x++mRBW5dUDI7JbXtMQ18/d496VSUmdj0iEoWPLY73hTagIlX3o/vjfcmBqZ016t1zNDthCPvVlhCcR8kk9JvYGC23YplbqrBl7teXeVFutzAyTKdOkZY0MjM4HaNfkM3J7c0lOcizA5ygpCyQ0BpiVumbVENpS6/XPPhcP4oQDizWiSw96Tl0wyqdlB6MeGOXODbYi9GPYopwEGGR5UqjtzjfzOKGRtUQuB+NUIXGAJBmsTNxBB0v1OPr5vFgnF4ux8ayjJys946jP94cMZu8GGpSWueQCQwFMFU3syE1cBfPVtpEvkZ9 schafer@CLSchaferUL
write_files:
  - path: /etc/ssh/import_keys
    content: |
      gh:stephenprater
      gh:AndrewScibek
      gh:corbinlc
      gh:MatthewTighe
      gh:luongthomas

hostname: ${hostname}
