---
- name: Create Consul conf dir
  file:
    path: /etc/datadog-agent/conf.d/consul.d
    state: directory
    owner: dd-agent
    group: dd-agent
    mode: 0755

- name: Modify Consul Integration
  template:
    src: templates/consul.j2.yaml
    dest: /etc/datadog-agent/conf.d/consul.d/conf.yaml
    owner: dd-agent
    group: dd-agent
    mode: 0644

